[project]
name = "livekit-trugen-examples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "livekit-agents>=1.3.10",
    "livekit-plugins-google>=1.4.2",
    "livekit-plugins-trugen>=1.3.11",
]
